name: gemtexsurrogator
services:
  gemtexsurrogator:
    image: gemtex/surrogator:0.3.0
    container_name: gemtex_surrogator
    command: "--webservice"
    restart: unless-stopped
    ports:
      - '9015:8501'
